import type { AppProps } from "next/app";

import "@/styles/style.scss";
import { Provider } from "react-redux";
import { store, wrapper } from "@/redux/store";
import Head from "next/head";
import { Api } from "@/utils/api";
import { setUserData } from "@/redux/user/slice";

const App = ({ Component, ...rest }: AppProps) => {
  const { store, props } = wrapper.useWrappedStore(rest);

  return (
    <>
      <Head>
        <title>NeoCode | Форум</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Provider store={store}>
        <Component {...props.pageProps} />
      </Provider>
    </>
  );
};

App.getInitialProps = wrapper.getInitialAppProps(
  (store) =>
    async ({ ctx, Component }) => {
      try {
        const userData = await Api(ctx).user.getProfile();
        store.dispatch(setUserData(userData));
      } catch (err) {
        console.warn(err);
      }

      return {
        pageProps: Component.getInitialProps
          ? await Component.getInitialProps({ ...ctx, store })
          : {},
      };
    }
);

export default App;
