import { useSelectors } from "@/hooks/useSelectors";
import { wrapper } from "@/redux/store";
import { setUserData } from "@/redux/user/slice";
import "@/styles/style.scss";
import { Api } from "@/utils/api";
import type { AppProps } from "next/app";
import Head from "next/head";
import React from "react";
import { Provider } from "react-redux";

interface AppComponentProps {
  Component: any;
  props: any;
}

export const AppComponent: React.FC<AppComponentProps> = ({
  Component,
  props,
}) => {
  const { theme } = useSelectors((state) => state.user);

  React.useEffect(() => {
    document.body.classList.add(theme.toLowerCase());
    return () => {
      document.body.classList.remove(theme.toLowerCase());
    };
  }, [theme]);

  return <Component {...props.pageProps} />;
};

const App = ({ Component, ...rest }: AppProps) => {
  const { store, props } = wrapper.useWrappedStore(rest);

  return (
    <>
      <Head>
        <title>NeoCode | Форум</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/styles/atom-one-dark.min.css"
        />
      </Head>

      <Provider store={store}>
        <AppComponent Component={Component} props={props} />
      </Provider>
    </>
  );
};

App.getInitialProps = wrapper.getInitialAppProps(
  (store) =>
    async ({ ctx, Component }) => {
      try {
        const userData = await Api(ctx).user.getProfile();
        store.dispatch(setUserData(userData));
      } catch (err) {
        console.log("Error Authorization");
      }

      return {
        pageProps: Component.getInitialProps
          ? await Component.getInitialProps({ ...ctx, store })
          : {},
      };
    }
);

export default App;
